name: deoloy to heroku

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    #- name: install git
    #  run: sudo apt-get install -y git
    - name: git switch
      run: git switch -c master
    - name: deoloy to heroku
      env:
        HEROKU_APP: astapi-dev-blog
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master
